### ISSUE TITLE
Rename this library

### ISSUE THREAD

**Issue by andrewthad** [byteverse/small-bytearray-builder#11]
After https://github.com/andrewthad/small-bytearray-builder/pull/10, the name of this library is now completely wrong. I need to rename it to `bytes-builder` or something like that. I'm waiting to do this since it's going to be a minor annoyance.

**Comment by andrewthad** [comment]
I'm thinking either `bytes-builder` or `bytebuild`. Does anyone have any preferences one way or the other?

**Comment by mckeankylej** [comment]
bytebuild has nice synergy with bytesmith that’s my vote
